apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.5.3
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 5m
  values:
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"

    ingress:
      enabled: true

      ingressClassName: nginx
      # annotations:
      #   cert-manager.io/cluster-issuer: "letsencrypt-production"

      hosts:
        - pihole.stndrs.home

      # tls:
      #  - secretName: pihole-tls
      #    hosts:
      #      - pihole.${domain}

    persistentVolumeClaim:
      enabled: true

    serviceDns:
      type: LoadBalancer

    serviceWeb:
      type: LoadBalancer
